"""Phase 10 schema: portfolio holdings/transactions + watchlist

Revision ID: 29891defa460
Revises: 268835023399
Create Date: 2026-07-27 20:58:59.472969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29891defa460'
down_revision: Union[str, Sequence[str], None] = '268835023399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_holdings',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('asset_type', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('portfolio_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=4), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('added_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('portfolio_transactions')
    op.drop_table('portfolio_holdings')
    # ### end Alembic commands ###
