"""phase 1 data layer schema

Revision ID: 5764ac3432c0
Revises: 596a4bb12963
Create Date: 2026-07-22 00:13:24.720556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5764ac3432c0'
down_revision: Union[str, Sequence[str], None] = '596a4bb12963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_indicators',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('indicator_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'indicator_name')
    )
    op.create_table('refresh_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=50), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickers',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('asset_type', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('analyst_consensus',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('strong_buy', sa.Integer(), nullable=False),
    sa.Column('buy', sa.Integer(), nullable=False),
    sa.Column('hold', sa.Integer(), nullable=False),
    sa.Column('sell', sa.Integer(), nullable=False),
    sa.Column('strong_sell', sa.Integer(), nullable=False),
    sa.Column('mean_price_target', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date')
    )
    op.create_table('fundamentals_snapshot',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('ps', sa.Float(), nullable=True),
    sa.Column('peg', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('debt_equity', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('fcf', sa.Float(), nullable=True),
    sa.Column('div_yield', sa.Float(), nullable=True),
    sa.Column('sector_specific_metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date')
    )
    op.create_table('index_membership_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('added_date', sa.Date(), nullable=False),
    sa.Column('removed_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('index_membership_history')
    op.drop_table('fundamentals_snapshot')
    op.drop_table('analyst_consensus')
    op.drop_table('tickers')
    op.drop_table('refresh_log')
    op.drop_table('macro_indicators')
    # ### end Alembic commands ###
