"""initial empty schema

Revision ID: 596a4bb12963
Revises:
Create Date: 2026-07-21 20:27:23.041756

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "596a4bb12963"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
