"""Phase 4/5 schema: news intelligence + smart money tables

Revision ID: 5e4a89d1a9e5
Revises: 1ebb26e534ea
Create Date: 2026-07-22 14:20:21.985905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4a89d1a9e5'
down_revision: Union[str, Sequence[str], None] = '1ebb26e534ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_calendar',
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('event_date', 'event_name')
    )
    op.create_table('market_regime',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vix_level', sa.Float(), nullable=True),
    sa.Column('breadth_pct_above_200dma', sa.Float(), nullable=True),
    sa.Column('macro_news_tone', sa.Float(), nullable=True),
    sa.Column('yield_curve_spread', sa.Float(), nullable=True),
    sa.Column('regime_score', sa.Float(), nullable=True),
    sa.Column('regime_label', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('news_events',
    sa.Column('article_id', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('matched_symbols', sa.JSON(), nullable=True),
    sa.Column('matched_theme', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('thematic_baskets',
    sa.Column('theme_name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('theme_name', 'symbol')
    )
    op.create_table('insider_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('insider_name', sa.String(length=255), nullable=True),
    sa.Column('insider_title', sa.String(length=255), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('transaction_code', sa.String(length=5), nullable=True),
    sa.Column('acquired_disposed_code', sa.String(length=1), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price_per_share', sa.Float(), nullable=True),
    sa.Column('shares_owned_after', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'insider_name', 'transaction_date', 'transaction_code', 'shares', name='uq_insider_transaction')
    )
    op.create_table('institutional_ownership',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('quarter_end_date', sa.Date(), nullable=False),
    sa.Column('total_shares_held', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('num_filers', sa.Integer(), nullable=True),
    sa.Column('change_from_prior_quarter', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'quarter_end_date')
    )
    op.create_table('options_signals',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('expiration', sa.String(length=10), nullable=True),
    sa.Column('put_call_ratio', sa.Float(), nullable=True),
    sa.Column('atm_implied_volatility', sa.Float(), nullable=True),
    sa.Column('iv_rank', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_table('sentiment_scores',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('mention_volume', sa.Integer(), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date', 'source')
    )
    op.create_table('short_interest',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('pct_float_short', sa.Float(), nullable=True),
    sa.Column('days_to_cover', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_interest')
    op.drop_table('sentiment_scores')
    op.drop_table('options_signals')
    op.drop_table('institutional_ownership')
    op.drop_table('insider_transactions')
    op.drop_table('thematic_baskets')
    op.drop_table('news_events')
    op.drop_table('market_regime')
    op.drop_table('economic_calendar')
    # ### end Alembic commands ###
