"""Phase 6 schema: composite_scores table

Revision ID: 999438f3b47e
Revises: 5e4a89d1a9e5
Create Date: 2026-07-22 15:19:44.532260

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "999438f3b47e"
down_revision: Union[str, Sequence[str], None] = "5e4a89d1a9e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "composite_scores",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("profile", sa.String(length=30), nullable=False),
        sa.Column("fundamental_score", sa.Float(), nullable=True),
        sa.Column("technical_score", sa.Float(), nullable=True),
        sa.Column("analyst_score", sa.Float(), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("momentum_score", sa.Float(), nullable=True),
        sa.Column("industry_macro_score", sa.Float(), nullable=True),
        sa.Column("smart_money_score", sa.Float(), nullable=True),
        sa.Column("composite_score", sa.Float(), nullable=False),
        sa.Column("percentile_rank", sa.Float(), nullable=True),
        sa.Column("rating", sa.String(length=15), nullable=False),
        sa.Column("data_confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["tickers.symbol"],
        ),
        sa.PrimaryKeyConstraint("symbol", "date", "profile"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("composite_scores")
    # ### end Alembic commands ###
