"""Stock Detail — the per-ticker deep dive (Sections 8, 12 page 3).

Section 8 specifies the contents: price chart with indicators and detected
patterns, a radar of the sub-scores, the forecast fan chart, the
analyst-vs-algorithm comparison, the "what's driving this" news feed, and an
optional LLM narrative.

Two deliberate choices:

* **Every forecast is shown next to its own track record.** Section 7.6:
  "Show the model's own historical hit-rate/accuracy stat *alongside every
  individual forecast* in the UI, not just on a separate backtest page — a
  forecast without its own track record next to it invites more confidence
  than it's earned." So `historical_hit_rate` is a column of the forecast
  table, not a footnote elsewhere.
* **The LLM narrative is strictly optional and visibly so.** With no provider
  configured the section simply doesn't render; nothing else on the page
  changes, which is Section 11's "the core engine has zero dependency on it"
  made visible rather than merely claimed.
"""

import pandas as pd
import streamlit as st

from lib import charts, data
from lib.format import (
    confidence_label,
    format_percent,
    format_price,
    format_score,
    format_signed_percent,
    freshness_label,
    humanize,
    rating_label,
)
from quantpulse.analysis.investor_profiles import CATEGORIES
from quantpulse.llm import narrative as llm_narrative
from quantpulse.llm.providers import get_provider

st.set_page_config(page_title="QuantPulse — Stock Detail", page_icon="🔬", layout="wide")

SCORE_COLUMNS = {category: f"{category}_score" for category in CATEGORIES}


def render_analyst_comparison(symbol: str, row: pd.Series) -> None:
    """Section 7.4's "our algorithm says X, Wall Street says Y" panel."""
    st.subheader("Algorithm vs Wall Street")
    consensus = data.analyst_consensus(symbol)
    left, right = st.columns(2)
    left.metric("QuantPulse rating", rating_label(row["rating"]))
    left.caption(
        f"Composite {format_score(row['composite_score'])} · "
        f"{confidence_label(row['data_confidence'])}"
    )
    if consensus is None:
        right.metric("Analyst consensus", "—")
        right.caption("No analyst coverage stored for this symbol.")
        return

    counts = {
        "Strong Buy": consensus["strong_buy"],
        "Buy": consensus["buy"],
        "Hold": consensus["hold"],
        "Sell": consensus["sell"],
        "Strong Sell": consensus["strong_sell"],
    }
    total = sum(counts.values())
    leading = max(counts, key=lambda k: counts[k]) if total else "—"
    right.metric("Analyst consensus", leading)
    target = consensus["mean_price_target"]
    right.caption(
        f"{total} analysts · mean target {format_price(target)} · as of {consensus['as_of_date']}"
    )
    st.plotly_chart(charts.sector_bar(counts, title="Analyst rating counts"), width="stretch")


def render_narrative(symbol: str, row: pd.Series) -> None:
    """Section 11's optional "why this rating" paragraph — absent when no LLM is set up."""
    if get_provider() is None:
        return
    st.subheader("Plain-English summary")
    st.caption(
        "Generated by the optional LLM layer from the numbers above — it narrates "
        "them, it does not compute or add any."
    )
    sub_scores = {
        category: (
            None if pd.isna(row[SCORE_COLUMNS[category]]) else float(row[SCORE_COLUMNS[category]])
        )
        for category in CATEGORIES
    }
    context = llm_narrative.RatingNarrative(
        symbol=symbol,
        rating=row["rating"],
        composite_score=float(row["composite_score"]),
        sub_scores=sub_scores,
        percentile_rank=None if pd.isna(row["percentile_rank"]) else float(row["percentile_rank"]),
        data_confidence=(
            None if pd.isna(row["data_confidence"]) else float(row["data_confidence"])
        ),
        as_of=row["date"],
    )
    with st.spinner("Narrating…"):
        text = llm_narrative.explain_rating(context)
    if text:
        st.info(text)
    else:
        st.caption("The LLM layer is configured but did not return a summary this time.")


def main() -> None:
    st.title("🔬 Stock Detail")
    rows = data.screener_rows()
    if rows.empty:
        st.info("No scored symbols yet — run `scripts/refresh_data.py` first.")
        return

    symbols = rows["symbol"].tolist()
    preselected = st.session_state.get("detail_symbol")
    index = symbols.index(preselected) if preselected in symbols else 0
    symbol = st.selectbox("Symbol", symbols, index=index)
    st.session_state["detail_symbol"] = symbol

    row = rows[rows["symbol"] == symbol].iloc[0]
    header = st.columns([2, 1, 1, 1])
    header[0].markdown(f"### {symbol} — {row['name'] or ''}")
    header[0].caption(row["sector"] or "Sector unknown")
    header[1].metric("Rating", rating_label(row["rating"]))
    header[2].metric("Composite", format_score(row["composite_score"]))
    header[3].metric("Percentile", format_score(row["percentile_rank"], digits=0))
    st.caption(
        f"{confidence_label(row['data_confidence'])} · scored {freshness_label(row['date'])}"
    )

    bars = data.ohlcv(symbol, lookback_days=400)
    overlays: dict[str, pd.Series] = {}
    if not bars.empty and len(bars) >= 50:
        overlays["SMA 50"] = bars["close"].rolling(50).mean()
    if not bars.empty and len(bars) >= 200:
        overlays["SMA 200"] = bars["close"].rolling(200).mean()
    st.plotly_chart(charts.price_chart(bars, overlays=overlays), width="stretch")

    left, right = st.columns(2)
    with left:
        st.subheader("Sub-scores")
        sub_scores = {
            category: (
                None
                if pd.isna(row[SCORE_COLUMNS[category]])
                else float(row[SCORE_COLUMNS[category]])
            )
            for category in CATEGORIES
        }
        st.plotly_chart(charts.subscore_radar(sub_scores, name=symbol), width="stretch")
        st.caption(
            "Categories with no data are omitted rather than plotted at zero — "
            "a missing score is not a bad score."
        )
    with right:
        st.subheader("Detected patterns")
        found = data.patterns(symbol)
        if found.empty:
            st.caption("No chart or candlestick patterns detected in the last 120 days.")
        else:
            display = found.copy()
            display["Pattern"] = display["pattern_type"].map(humanize)
            display["Direction"] = display["direction"].map(humanize)
            st.dataframe(
                display[["date", "Pattern", "Direction", "confidence"]]
                .rename(columns={"date": "Date", "confidence": "Confidence"})
                .style.format({"Confidence": "{:.2f}"}),
                hide_index=True,
                width="stretch",
            )

    st.divider()
    st.subheader("Forecast")
    forecast_rows = data.forecasts(symbol)
    if forecast_rows.empty:
        st.caption("No forecasts generated for this symbol yet.")
    else:
        models = sorted(forecast_rows["model_name"].unique())
        model = st.selectbox("Model", models, index=0)
        st.plotly_chart(
            charts.forecast_fan_chart(bars, forecast_rows, model_name=model), width="stretch"
        )
        table = forecast_rows[forecast_rows["model_name"] == model].copy()
        table["Return"] = table["point_return"].map(format_signed_percent)
        table["Hit rate"] = table["historical_hit_rate"].map(
            lambda v: "—" if pd.isna(v) else format_percent(v, digits=0)
        )
        st.dataframe(
            table[
                ["horizon_days", "Return", "point_price", "lower_price", "upper_price", "Hit rate"]
            ].rename(
                columns={
                    "horizon_days": "Horizon (days)",
                    "point_price": "Target",
                    "lower_price": "Low",
                    "upper_price": "High",
                }
            ),
            hide_index=True,
            width="stretch",
        )
        st.caption(
            "**Hit rate** is this model's own out-of-sample directional accuracy at that "
            "horizon (Section 7.6) — shown next to the forecast, not hidden on another page."
        )

    st.divider()
    render_analyst_comparison(symbol, row)

    st.divider()
    st.subheader("What's driving this")
    news = data.symbol_news(symbol, limit=10)
    if news.empty:
        st.caption("No Tier-1 articles matched this symbol in the last three weeks.")
    else:
        for item in news.itertuples():
            title = item.title or "(untitled)"
            headline = f"[{title}]({item.source_url})" if item.source_url else title
            st.markdown(f"**{headline}**")
            event = humanize(item.event_type) if item.event_type else "unclassified"
            st.caption(
                f"{event} · sentiment {format_score(item.sentiment_score, digits=2)} · "
                f"{item.source or 'unknown source'}"
            )

    st.divider()
    render_narrative(symbol, row)


main()
